//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.19 at 11:46:10 PM ICT 
//


package vensys.embryo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides information on the charges related to the payment transaction.
 * 
 * <p>Java class for ChargesPerTransaction3__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChargesPerTransaction3__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ChrgsId" type="{urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02}CBPR_RestrictedFINXMax16Text"/&gt;
 *         &lt;element name="Rcrd" type="{urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02}ChargesPerTransactionRecord3__1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChargesPerTransaction3__1", propOrder = {
    "chrgsId",
    "rcrd"
})
public class ChargesPerTransaction31 {

    @XmlElement(name = "ChrgsId", required = true)
    protected String chrgsId;
    @XmlElement(name = "Rcrd", required = true)
    protected ChargesPerTransactionRecord31 rcrd;

    /**
     * Gets the value of the chrgsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChrgsId() {
        return chrgsId;
    }

    /**
     * Sets the value of the chrgsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChrgsId(String value) {
        this.chrgsId = value;
    }

    /**
     * Gets the value of the rcrd property.
     * 
     * @return
     *     possible object is
     *     {@link ChargesPerTransactionRecord31 }
     *     
     */
    public ChargesPerTransactionRecord31 getRcrd() {
        return rcrd;
    }

    /**
     * Sets the value of the rcrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargesPerTransactionRecord31 }
     *     
     */
    public void setRcrd(ChargesPerTransactionRecord31 value) {
        this.rcrd = value;
    }

}
