//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.19 at 11:46:10 PM ICT 
//


package vensys.embryo;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Set of characteristics shared by all individual charges records included in the message.
 * 
 * <p>Java class for GroupHeader115__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupHeader115__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MsgId" type="{urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02}CBPR_RestrictedFINXMax35Text"/&gt;
 *         &lt;element name="CreDtTm" type="{urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02}CBPR_DateTime"/&gt;
 *         &lt;element name="ChrgsRqstr" type="{urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02}BranchAndFinancialInstitutionIdentification8__1"/&gt;
 *         &lt;element name="ChrgsAcctAgt" type="{urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02}BranchAndFinancialInstitutionIdentification8__1" minOccurs="0"/&gt;
 *         &lt;element name="ChrgsAcctAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02}CashAccount40__1" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupHeader115__1", propOrder = {
    "msgId",
    "creDtTm",
    "chrgsRqstr",
    "chrgsAcctAgt",
    "chrgsAcctAgtAcct"
})
public class GroupHeader1151 {

    @XmlElement(name = "MsgId", required = true)
    protected String msgId;
    @XmlElement(name = "CreDtTm", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creDtTm;
    @XmlElement(name = "ChrgsRqstr", required = true)
    protected BranchAndFinancialInstitutionIdentification81 chrgsRqstr;
    @XmlElement(name = "ChrgsAcctAgt")
    protected BranchAndFinancialInstitutionIdentification81 chrgsAcctAgt;
    @XmlElement(name = "ChrgsAcctAgtAcct")
    protected CashAccount401 chrgsAcctAgtAcct;

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the creDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreDtTm() {
        return creDtTm;
    }

    /**
     * Sets the value of the creDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreDtTm(XMLGregorianCalendar value) {
        this.creDtTm = value;
    }

    /**
     * Gets the value of the chrgsRqstr property.
     * 
     * @return
     *     possible object is
     *     {@link BranchAndFinancialInstitutionIdentification81 }
     *     
     */
    public BranchAndFinancialInstitutionIdentification81 getChrgsRqstr() {
        return chrgsRqstr;
    }

    /**
     * Sets the value of the chrgsRqstr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchAndFinancialInstitutionIdentification81 }
     *     
     */
    public void setChrgsRqstr(BranchAndFinancialInstitutionIdentification81 value) {
        this.chrgsRqstr = value;
    }

    /**
     * Gets the value of the chrgsAcctAgt property.
     * 
     * @return
     *     possible object is
     *     {@link BranchAndFinancialInstitutionIdentification81 }
     *     
     */
    public BranchAndFinancialInstitutionIdentification81 getChrgsAcctAgt() {
        return chrgsAcctAgt;
    }

    /**
     * Sets the value of the chrgsAcctAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchAndFinancialInstitutionIdentification81 }
     *     
     */
    public void setChrgsAcctAgt(BranchAndFinancialInstitutionIdentification81 value) {
        this.chrgsAcctAgt = value;
    }

    /**
     * Gets the value of the chrgsAcctAgtAcct property.
     * 
     * @return
     *     possible object is
     *     {@link CashAccount401 }
     *     
     */
    public CashAccount401 getChrgsAcctAgtAcct() {
        return chrgsAcctAgtAcct;
    }

    /**
     * Sets the value of the chrgsAcctAgtAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashAccount401 }
     *     
     */
    public void setChrgsAcctAgtAcct(CashAccount401 value) {
        this.chrgsAcctAgtAcct = value;
    }

}
