//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.19 at 11:46:10 PM ICT 
//


package vensys.embryo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.draft5camt_106_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.draft5camt_106_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VensysCamt10600102 }
     * 
     */
    public VensysCamt10600102 createDocument() {
        return new VensysCamt10600102();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice1 }
     * 
     */
    public AccountSchemeName1Choice1 createAccountSchemeName1Choice1() {
        return new AccountSchemeName1Choice1();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification81 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification81 createBranchAndFinancialInstitutionIdentification81() {
        return new BranchAndFinancialInstitutionIdentification81();
    }

    /**
     * Create an instance of {@link CBPRAmount }
     * 
     */
    public CBPRAmount createCBPRAmount() {
        return new CBPRAmount();
    }

    /**
     * Create an instance of {@link CashAccount401 }
     * 
     */
    public CashAccount401 createCashAccount401() {
        return new CashAccount401();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice1 }
     * 
     */
    public CashAccountType2Choice1 createCashAccountType2Choice1() {
        return new CashAccountType2Choice1();
    }

    /**
     * Create an instance of {@link ChargeType3Choice1 }
     * 
     */
    public ChargeType3Choice1 createChargeType3Choice1() {
        return new ChargeType3Choice1();
    }

    /**
     * Create an instance of {@link Charges3Choice1 }
     * 
     */
    public Charges3Choice1 createCharges3Choice1() {
        return new Charges3Choice1();
    }

    /**
     * Create an instance of {@link ChargesBreakdown11 }
     * 
     */
    public ChargesBreakdown11 createChargesBreakdown11() {
        return new ChargesBreakdown11();
    }

    /**
     * Create an instance of {@link ChargesPaymentRequestV02 }
     * 
     */
    public ChargesPaymentRequestV02 createChargesPaymentRequestV02() {
        return new ChargesPaymentRequestV02();
    }

    /**
     * Create an instance of {@link ChargesPerTransaction31 }
     * 
     */
    public ChargesPerTransaction31 createChargesPerTransaction31() {
        return new ChargesPerTransaction31();
    }

    /**
     * Create an instance of {@link ChargesPerTransactionRecord31 }
     * 
     */
    public ChargesPerTransactionRecord31 createChargesPerTransactionRecord31() {
        return new ChargesPerTransactionRecord31();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice1 }
     * 
     */
    public ClearingSystemIdentification2Choice1 createClearingSystemIdentification2Choice1() {
        return new ClearingSystemIdentification2Choice1();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification231 }
     * 
     */
    public FinancialInstitutionIdentification231 createFinancialInstitutionIdentification231() {
        return new FinancialInstitutionIdentification231();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link GroupHeader1151 }
     * 
     */
    public GroupHeader1151 createGroupHeader1151() {
        return new GroupHeader1151();
    }

    /**
     * Create an instance of {@link InstructionForInstructedAgent11 }
     * 
     */
    public InstructionForInstructedAgent11 createInstructionForInstructedAgent11() {
        return new InstructionForInstructedAgent11();
    }

    /**
     * Create an instance of {@link PostalAddress271 }
     * 
     */
    public PostalAddress271 createPostalAddress271() {
        return new PostalAddress271();
    }

    /**
     * Create an instance of {@link ProxyAccountIdentification11 }
     * 
     */
    public ProxyAccountIdentification11 createProxyAccountIdentification11() {
        return new ProxyAccountIdentification11();
    }

    /**
     * Create an instance of {@link ProxyAccountType1Choice1 }
     * 
     */
    public ProxyAccountType1Choice1 createProxyAccountType1Choice1() {
        return new ProxyAccountType1Choice1();
    }

    /**
     * Create an instance of {@link TotalCharges81 }
     * 
     */
    public TotalCharges81 createTotalCharges81() {
        return new TotalCharges81();
    }

    /**
     * Create an instance of {@link TransactionReferences71 }
     * 
     */
    public TransactionReferences71 createTransactionReferences71() {
        return new TransactionReferences71();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VensysCamt10600102 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VensysCamt10600102 }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02", name = "Document")
    public JAXBElement<VensysCamt10600102> createDocument(VensysCamt10600102 value) {
        return new JAXBElement<VensysCamt10600102>(_Document_QNAME, VensysCamt10600102.class, null, value);
    }

}
