//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.19 at 11:46:10 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02",

        xmlns = {@XmlNs(prefix = "",
                namespaceURI = "urn:iso:std:iso:20022:tech:xsd:DRAFT5camt.106.001.02")}
        ,elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vensys.embryo;

import javax.xml.bind.annotation.XmlNs;